# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  build:
    strategy:
      matrix:
        runner: [ 'ubuntu-24.04' ]
        go: [ '1.22.0', '1.23.1' ]

    runs-on: ${{ matrix.runner }}

    name: ${{ matrix.runner }}, golang:${{ matrix.go }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}
          cache-dependency-path: |
            go.sum

      - name: Test
        run: go clean -testcache && go test -coverprofile=coverage.out -cover ./...

      - name: Coverage
        run: go tool cover -html=./coverage.out -o ./coverage.html
